# -*- coding: utf-8 -*-
"""DisTweet-Bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsIUIwXjXNYqsAPOV-725e-WhqTINDfh
"""

import pandas as pd
df = pd.read_csv("train.csv",encoding='ISO-8859-1')
df.head(5)

df = df.drop(['id','keyword','location'],axis=1)
df.head()

df['target'].value_counts()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'],df['target'], stratify=df['target'])

!pip install tensorflow_text

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text-layer')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)
d_layer = tf.keras.layers.Dropout(0.1, name="dropout-layer")(outputs['pooled_output'])
d_layer = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(d_layer)
model = tf.keras.Model(inputs=[text_input], outputs = [d_layer])

m= [tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')]
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=m)

!nvidia-smi

model.fit(X_train, y_train, epochs=10)

model.evaluate(X_test, y_test)



model.fit(df['text'],df['target'], epochs=15)



model.save('model-tweet.h5')





